# Generated by Django 5.1.2 on 2024-11-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='contact_info',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='nid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service_provider',
            name='provider_id',
            field=models.IntegerField(),
        ),
    ]
