# Generated by Django 5.1.2 on 2024-12-01 21:41

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.provider_directory_path),
        ),
    ]
