# Generated by Django 5.1.2 on 2024-11-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_consumer_contact_info_alter_consumer_nid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='rating',
        ),
    ]
