# Generated by Django 5.1.2 on 2024-12-01 22:50

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_provider_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.provider_directory_path),
        ),
    ]
