# Generated by Django 5.1.2 on 2024-11-06 19:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_consumer_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_provider',
            new_name='provider',
        ),
    ]
