# Generated by Django 5.1.2 on 2025-03-23 18:24

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_consumer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.consumer_directory_path),
        ),
        migrations.AlterField(
            model_name='provider',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='provider',
            name='total_work',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='rate_per_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicehistory',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('rated', 'Rated'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
