# Generated by Django 5.1.2 on 2025-03-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_consumer_picture_alter_provider_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='wallet_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='earned_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
