# Generated by Django 5.1.2 on 2024-11-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_service_provider_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='total_work',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='consumer_id',
            field=models.IntegerField(),
        ),
    ]
