# Generated by Django 5.1.2 on 2024-11-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_provider_rating_provider_total_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='contact_info',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='location',
            field=models.CharField(default='Default Location', max_length=200),
        ),
        migrations.AddField(
            model_name='provider',
            name='nid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
