# Generated by Django 5.1.2 on 2024-11-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_provider_contact_info_provider_location_provider_nid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='user',
        ),
        migrations.AddField(
            model_name='provider',
            name='password',
            field=models.CharField(default='1234', max_length=128),
        ),
    ]
